export const exercises = [
    {
        id: 1,
        "work": "Barbell Squat",
        "sets": 3,
        "reps": 6,
        "weight": 40,
    },
    {
        id: 2,
        "work": "Bench Press",
        "sets": 3,
        "reps": 6,
        "weight": 40,
    },
    {
        id: 3,
        "work": "Pull ups",
        "sets": 3,
        "reps": 6,
        "weight": 0,
    },
    {
        id: 4,
        "work": "Hip Thrust",
        "sets": 2,
        "reps": 6,
        "weight": 0,
    },
    {
        id: 5,
        "work": "Seated Leg Curl",
        "sets": 2,
        "reps": 12,
        "weight": 20,
    },
    {
        id: 6,
        "work": "Calf Raise",
        "sets": 2,
        "reps": 12,
        "weight": 0,
    },
    {
        id: 7,
        "work": "Overhead Press",
        "sets": 2,
        "reps": 12,
        "weight": 15,
    },
    {
        id: 8,
        "work": "Cable Row",
        "sets": 2,
        "reps": 12,
        "weight": 50,
    },
    {
        id: 9,
        "work": "Lateral Raise",
        "sets": 2,
        "reps": 12,
        "weight": 15,
    },
    {
        id: 10,
        "work": "Face Pull",
        "sets": 3,
        "reps": 12,
        "weight": 50,
    },
    {
        id: 11,
        "work": "Bicep Curls",
        "sets": 2,
        "reps": 12,
        "weight": 20,
    },
    {
        id: 12,
        "work": "Tricep Extension",
        "sets": 3,
        "reps": 12,
        "weight": 40,
    },
    {
        id: 13,
        "work": "Cable Crunch",
        "sets": 3,
        "reps": 12,
        "weight": 50,
    },
]

export default exercises